### PR TITLE
Update Projects.md

### PR DESCRIPTION
**Pull request by Bavishyath**

### CODE REVIEW

**Review by thelordzeus — CHANGES_REQUESTED** [review]
Still the link is not working, showing error 404.

paste the link below I'll add it manually

**Comment by thelordzeus** [comment]
@Bavishyath Kindly paste the correct link below in this conversation, I'll add your project link manually

**Review by thelordzeus — APPROVED** [review]
Looks good to go

**Comment by Hemswaroopsai** [comment]
paste this link bro https://github.com/Hemswaroopsai/18CSE301J-INFO_-VIS/blob/main/Project

**Pull request merged**
